name: Rector CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/setup
      with:
        php-version: '8.3'
        php-extensions: 'mbstring, xml, tokenizer, curl, json'

    - name: Cache Rector cache
      uses: actions/cache@v4
      with:
        path: storage/rector
        key: ${{ runner.os }}-rector-${{ hashFiles('**/rector.php') }}
        restore-keys: ${{ runner.os }}-rector-

    - name: Run Rector
      run: |
        vendor/bin/rector process --ansi

    - name: Validate Rector changes
      run: |
        git diff --exit-code
